FilePath:
  output_dir: result_112021
  experiment_name: omega30_3_180
  plib_file: plib_data/plib_combined.h5
  pmt_file: plib_data/pmt_loc.csv
  lut_file: plib_data/lut_log10_1e-5.h5
Model:
  in_features: 3
  out_features: 180
  hidden_features: 512
  hidden_layers: 5
  omega: 30
Training:
  batch_size: 65536
  num_epochs: 1000
  learning_rate: 5.e-5
  steps_til_summary: 500
  epochs_til_checkpoint: 100