FilePath:
  output_dir: /sdf/home/m/mlei/optical_sim/logs/results_010621
  experiment_name: plib_toy_train
  plib_file: plib_data/plib_toy.h5
  pmt_file: plib_data/pmt_loc.csv
  lut_file: 
Model:
  in_features: 3
  out_features: 180
  hidden_features: 512
  hidden_layers: 5
  omega: 30
Training:
  batch_size: 65536
  num_epochs: 1000
  learning_rate: 5.e-5
  patience: 50
  steps_til_summary: 100
  epochs_til_checkpoint: 100